# Site
title: Interactivos?'18
subtitle: Tecnosfera Rural

# URL
url: https://interactivos.silo.org.br
baseurl: '/2018'
silo_url: https://silo.org.br
permalink: :categories/:title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 8666
future: false
theme: null

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "post"

# Data
social:
  facebook: "https://www.facebook.com/silo.arte.latitude.rural"
  instagram: "https://www.instagram.com/silo.arte.e.latitude.rural"
  github: "https://github.com/associacaosilo"
  twitter: "https://twitter.com/SiloLatitude"
  youtube: ""
  vimeo: ""
  soundcloud: ""
  tumblr: ""
  pinterest: ""
  envelope-o: "mailto:interactivos@silo.org.br"
twitter_user: "SiloLatitude"
